# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terragrunt"
    key                  = "chrille-bolaget-01/staging/global/resource_groups/terraform.tfstate"
    resource_group_name  = "cloudshellstorage"
    storage_account_name = "chrillecloudstorage"
    subscription_id      = "dd7b30f8-c637-48ab-a9c3-ed3dc4f285a9"
  }
}
