# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        azurerm = {
          source = "hashicorp/azurerm"
          version = "2.95.0"
        }
      }
    }

    provider "azurerm" {
        features {}
        subscription_id = "dd7b30f8-c637-48ab-a9c3-ed3dc4f285a9"
    }
